/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STATE_H_RPCGEN
#define _STATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define STATE_PROG 0x20000001
#define STATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define STATE_PROC 1
extern  void * state_proc_1(void *, CLIENT *);
extern  void * state_proc_1_svc(void *, struct svc_req *);
extern int state_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define STATE_PROC 1
extern  void * state_proc_1();
extern  void * state_proc_1_svc();
extern int state_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STATE_H_RPCGEN */
