/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "state.h"
#include <stdio.h>

void *
state_proc_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("Hello world!\n");

	return (void *) &result;
}
